### ISSUE TITLE
Crash when typing new InternalsVisibleTo-Attribute

### ISSUE THREAD

**Issue by BADF00D** [BADF00D/InternalsVisibleToFixer#6]
```chsarp
[assembly: InternalsVisibleTo(
```

Crashes the extension with
```charp
System.NullReferenceException : Object reference not set to an instance of an object.
   at InternalsVisibleToFixer.DistanceCalculation.LevensteinDistanceCalculator.CalculateDistance(String first,String second)
   at InternalsVisibleToFixer.ProposalGeneration.ProposalGenerator.<>c__DisplayClass3_0.<Generate>b__0(String reference)
   at System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements,Int32 count)
   at System.Linq.EnumerableSorter`1.Sort(TElement[] elements,Int32 count)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at async InternalsVisibleToFixer.InternalsVisibleToCodeFixProvider.RegisterCodeFixesAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformActionAsync(<Unknown Parameters>)
```

**Comment by BADF00D** [comment]
Part of release 0.3
